# Generated by Django 5.2.1 on 2025-06-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
