# Generated by Django 5.2.1 on 2025-06-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_project_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
