# Generated by Django 5.2.1 on 2025-06-29 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_project_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_name',
        ),
    ]
