# Generated by Django 5.2.1 on 2025-06-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_project_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_name',
            field=models.CharField(blank=True, help_text='Enter the base name of the image in static/images/, e.g., project1', max_length=200, null=True),
        ),
    ]
